# Generated by Django 4.2.11 on 2024-04-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_alter_home_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='slug',
            field=models.SlugField(verbose_name='slug'),
        ),
    ]
